baseurl         = "https://silly-keller-f2dfe1.netlify.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "syncster31"
  subtitle    = "Engineer..Coder"

  cover       = "images/cover-photo.jpeg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "syncster31"
  fbName = "alexius.sayco"
  githubName = "alexiusacademia"

  logo = ""
  orgName = "sync"
  orgWebsite = ""
  orgDescription = ""

  author = "syncster31"
  authorAvatar = "https://avatars2.githubusercontent.com/u/19258246?s=460&v=4"
  authorLocation = "Tarlac City, PH"
  authorWebsite = "https://alexiusacademia.com"
  authorDescription = "Engineer..Developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Projects"
  url = "/tags/projects/"
  weight = 100

[[menu.main]]
  name = "Motivation"
  url = "/categories/motivation/"
  weight = 99
